grpc.host=185.185.143.231
grpc.port=5055

mail.base-url=http://185.185.143.231:8085/mail/mail/messages
mail.timeout.ms=30000
mail.default-limit=50

test.user.default-password=Qwerty123!
test.user.new-password=NewQwerty123!